# ASP.NET Core
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure for Students(657b5b3f-66c5-4968-9779-8ceacaf208ba)'
    command: 'build'
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
